version: '3'
services:
  mongo:
    image: mongo
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      - ./data:/data/db

  node:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '${NODE_PORT}:3000'
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DATABASE=${MONGO_DATABASE}
    volumes:
      - ./backend/src:/app/src

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=${HOST_IP}
    ports:
      - 19000:19000
      - 19001:19001
    volumes:
      - ./frontend:/app

